### ISSUE TITLE
Select Project Sections and Assign

### ISSUE THREAD

**Issue by rnagel3** [chingu-voyages/v17-toucans-team-01#31]
I believe we are going to select different HTML sections to work on? Each person could choose 1 section to work on and post here which section it is going to be.

**Comment by rnagel3** [comment]
We can wait on the global themes like colors and CSS.

Does anyone else use Sass? Just asking to plan ahead. I used it a bit in a personal project, and would recommend trying it if others are okay with it or interested in how it works. It's pretty straightforward.

**Comment by cgefx** [comment]
@rnagel3 I just added all of the sections as issues.  It's high level and just a place to start so we'll need to add more granular issues for each as we go.  

In terms of assigning sections, I don't think there's any need to choose and post.  Just grab one out of the backlog, assign yourself, move the issue to the "in progress" column in projects and get going.  

Part of agile is removing the complexity and time required in assigning work.  If its in the backlog and part of the sprint goal, its gotta get done, doesn't matter by whom 👍

**Comment by cgefx** [comment]
@rnagel3 I'm not opposed to using Sass.  Any reason why? It will add some complexity since we'll need to set up a task runner with it which I think means node as well?  I'm not super experienced with the setup but I've used it in projects before.  I don't think our project has tons of styles and we could get away with regular CSS if we had to, but would give Sass a shot if there was a good reason too.

**Comment by rnagel3** [comment]
I looked into it, and I think you're right. Let's stick with vanilla CSS!

**Comment by cgefx** [comment]
cool we can keep it as an option as the project grows, it might help if the CSS starts to get out of hand.
